spring:
  application:
    name: config
  cloud:
    config:       #配置中心服务端
      server:
        git:
          uri: https://github.com/Thornflower/config
          username: 1254041898@qq.com
          password: Xuling521
          #basedir:   #设置git存在本地的配置文件路径
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"